// flow-typed signature: 83c41a8649a83e602a75bbb0d8cbd0aa
// flow-typed version: <<STUB>>/redux-catch_v^1.3.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-catch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-catch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'redux-catch/index' {
  declare module.exports: $Exports<'redux-catch'>;
}
declare module 'redux-catch/index.js' {
  declare module.exports: $Exports<'redux-catch'>;
}
