// flow-typed signature: 2263d4c2e2da546b2f862ec85e1e21ed
// flow-typed version: <<STUB>>/redux-form-submit-saga_v^1.1.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-form-submit-saga'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-form-submit-saga' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-form-submit-saga/es/common' {
  declare module.exports: any;
}

declare module 'redux-form-submit-saga/es/create' {
  declare module.exports: any;
}

declare module 'redux-form-submit-saga/es/form-submit-saga' {
  declare module.exports: any;
}

declare module 'redux-form-submit-saga/es/immutable' {
  declare module.exports: any;
}

declare module 'redux-form-submit-saga/es/index' {
  declare module.exports: any;
}

declare module 'redux-form-submit-saga/immutable' {
  declare module.exports: any;
}

declare module 'redux-form-submit-saga/lib/common' {
  declare module.exports: any;
}

declare module 'redux-form-submit-saga/lib/create' {
  declare module.exports: any;
}

declare module 'redux-form-submit-saga/lib/form-submit-saga' {
  declare module.exports: any;
}

declare module 'redux-form-submit-saga/lib/immutable' {
  declare module.exports: any;
}

declare module 'redux-form-submit-saga/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-form-submit-saga/es/common.js' {
  declare module.exports: $Exports<'redux-form-submit-saga/es/common'>;
}
declare module 'redux-form-submit-saga/es/create.js' {
  declare module.exports: $Exports<'redux-form-submit-saga/es/create'>;
}
declare module 'redux-form-submit-saga/es/form-submit-saga.js' {
  declare module.exports: $Exports<'redux-form-submit-saga/es/form-submit-saga'>;
}
declare module 'redux-form-submit-saga/es/immutable.js' {
  declare module.exports: $Exports<'redux-form-submit-saga/es/immutable'>;
}
declare module 'redux-form-submit-saga/es/index.js' {
  declare module.exports: $Exports<'redux-form-submit-saga/es/index'>;
}
declare module 'redux-form-submit-saga/immutable.js' {
  declare module.exports: $Exports<'redux-form-submit-saga/immutable'>;
}
declare module 'redux-form-submit-saga/lib/common.js' {
  declare module.exports: $Exports<'redux-form-submit-saga/lib/common'>;
}
declare module 'redux-form-submit-saga/lib/create.js' {
  declare module.exports: $Exports<'redux-form-submit-saga/lib/create'>;
}
declare module 'redux-form-submit-saga/lib/form-submit-saga.js' {
  declare module.exports: $Exports<'redux-form-submit-saga/lib/form-submit-saga'>;
}
declare module 'redux-form-submit-saga/lib/immutable.js' {
  declare module.exports: $Exports<'redux-form-submit-saga/lib/immutable'>;
}
declare module 'redux-form-submit-saga/lib/index.js' {
  declare module.exports: $Exports<'redux-form-submit-saga/lib/index'>;
}
